[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.0"
[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.0"
[[constraint]]
  name = "k8s.io/client-go"
  version = "9.0.0"
